version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123456*
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
